# Generated by Django 5.1.4 on 2024-12-23 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_payment_address_and_more'),
        ('users', '0002_alter_address_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='payments', to='users.address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='shipments', to='users.address'),
        ),
    ]
