# Generated by Django 5.1.4 on 2024-12-23 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_image_alter_productimage_product_line'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
